name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze
        env:
          GITHUB_TOKEN: 9e0d5726-5248-4a6e-9b0e-aa2fe1036ebc
          SONAR_TOKEN: e62c84adbcfda79e46a9c096fbf892c15140994b
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=neojarvis-testing_9e0d5726-5248-4a6e-9b0e-aa2fe1036ebc
          -Dsonar.login=e62c84adbcfda79e46a9c096fbf892c15140994b
